name: 'build & test'

inputs:
    path:
        description: 'Relative path under $GITHUB_WORKSPACE where the repository is checked out'
        default: '.'

runs:
    using: 'docker'
    image: 'docker://kariyam/gcc-meson:10.2'
    args:
    - ${{ inputs.path }}
